---
- name: Setup load balancer server
  hosts: loadbalancer
  become: true
  remote_user: congdat

  tasks:
    - name: Install Nginx and Certbot
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - nginx
        - certbot
        - python3-certbot-nginx

    - name: Copy nginx.conf file
      ansible.builtin.copy:
        src: ../nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        mode: "0644"

    - name: Enable and start Nginx service
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started
